apiVersion: v1
kind: Service
metadata:
  name: archinsight-ai-api-service
spec:
  type: LoadBalancer
  selector:
    app: archinsight-ai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
